services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    cpus: 0.5  # Limits to 0.5 CPU cores
    cpu_shares: 512  # Lower CPU priority relative to redis
    mem_limit: 512m  # Hard memory limit of 512 MB
    mem_reservation: 256m  # Reserves 256 MB of memory
    memswap_limit: 512m  # Disables swap by matching mem_limit
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Swarm mode: Hard CPU limit
          memory: 512M  # Swarm mode: Hard memory limit
        reservations:
          cpus: '0.25'  # Swarm mode: Reserves 0.25 CPU cores
          memory: 256M  # Swarm mode: Reserves 256 MB

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server
    cpus: 0.75  # Limits to 0.75 CPU cores
    cpu_shares: 1024  # Higher CPU priority than nginx
    mem_limit: 256m  # Hard memory limit of 256 MB
    mem_reservation: 128m  # Reserves 128 MB of memory
    memswap_limit: 256m  # Disables swap
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 256M
        reservations:
          cpus: '0.5'
          memory: 128M